const fs = require('fs');
const PDFDocument = require('pdfkit');

const PAGE_MARGIN = 50;
const IMG_W = 150;
const IMG_H = 110;
const ROW_H = IMG_H + 40;

function fmt(ts) {
  if (!ts) return '—';
  return new Date(ts).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' });
}

function generateJobPdf(job, property, outputPath) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, size: 'A4' });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    doc.fontSize(20).fillColor('#111').text('Changeover Clean Report', { align: 'left' });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#666').text('Generated by CleanProof', { align: 'left' });
    doc.moveDown(1);

    doc.fontSize(12).fillColor('#111');
    doc.text(`Property: ${property.name}`);
    doc.text(`Address: ${property.address}`);
    doc.text(`Cleaner: ${job.cleanerName}`);
    doc.text(`Job started: ${fmt(job.startedAt)}`);
    doc.text(`Job completed: ${fmt(job.completedAt)}`);
    doc.moveDown(1);

    doc.fontSize(14).fillColor('#111').text('Checklist', { underline: true });
    doc.moveDown(0.5);

    job.items.forEach((item, idx) => {
      if (doc.y + ROW_H > doc.page.height - PAGE_MARGIN) {
        doc.addPage();
      }

      const status = item.done ? 'DONE' : 'NOT DONE';
      const statusColor = item.done ? '#1a7f37' : '#b42318';

      doc.fontSize(11).fillColor('#111').text(`${idx + 1}. ${item.name}`, { continued: true });
      doc.fillColor(statusColor).text(`   [${status}]`);
      doc.fillColor('#666').fontSize(9);

      const top = doc.y + 4;
      let leftX = PAGE_MARGIN;

      if (item.beforePhoto) {
        try {
          doc.image(item.beforePhoto, leftX, top, { width: IMG_W, height: IMG_H, fit: [IMG_W, IMG_H] });
        } catch (e) {
          // corrupt/missing image — skip silently, report still generates
        }
        doc.fontSize(8).fillColor('#666').text('Before', leftX, top + IMG_H + 2, { width: IMG_W, align: 'center' });
        if (item.beforePhotoAt) {
          doc.text(fmt(item.beforePhotoAt), leftX, top + IMG_H + 13, { width: IMG_W, align: 'center' });
        }
      }

      const rightX = leftX + IMG_W + 20;
      if (item.afterPhoto) {
        try {
          doc.image(item.afterPhoto, rightX, top, { width: IMG_W, height: IMG_H, fit: [IMG_W, IMG_H] });
        } catch (e) {
          // corrupt/missing image — skip silently, report still generates
        }
        doc.fontSize(8).fillColor('#666').text('After', rightX, top + IMG_H + 2, { width: IMG_W, align: 'center' });
        if (item.afterPhotoAt) {
          doc.text(fmt(item.afterPhotoAt), rightX, top + IMG_H + 13, { width: IMG_W, align: 'center' });
        }
      }

      let bottom = top;
      if (item.beforePhoto || item.afterPhoto) {
        bottom = top + IMG_H + 26;
      } else {
        bottom = top + 4;
      }
      doc.y = bottom;

      if (item.notes) {
        doc.fontSize(9).fillColor('#333').text(`Note: ${item.notes}`, PAGE_MARGIN, doc.y);
      }

      doc.moveDown(0.8);
    });

    doc.moveDown(1);
    doc.fontSize(8).fillColor('#999').text(
      `This report was generated automatically on ${fmt(Date.now())} and reflects photos and checklist entries captured on-site by the cleaner.`,
      { align: 'left' }
    );

    doc.end();
    stream.on('finish', () => resolve(outputPath));
    stream.on('error', reject);
  });
}

module.exports = { generateJobPdf };
